language: python
python:
  - "3.6.6"

# install dependencies
install:
  - pip install -r requirements.txt
# command to run tests

# run pytest and coveralls script
script:
  - coverage run --source=app -m pytest && coverage report

# then post the results to coveralls
after_success:
  - coveralls
