language: python
python:
  - "3.6.6"

# install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE api_tests;" -U postgres
  - psql -c "CREATE USER admin WITH PASSWORD 'admin123';" -U admin

# run pytest and coveralls script
script:
  - coverage run --source=app -m pytest && coverage report

# then post the results to coveralls
after_success:
  - coveralls
